export const PROTOCOL_CONFIG = {
  NETWORK_NAME: 'Sepolia Testnet',
  CHAIN_ID: 11155111,
  DEFAULT_POLL_INTERVAL_MS: 4000,
  CACHE_TTL_SECONDS: 2,
  MAX_CIRCLES_PER_QUERY: 50,
  AUCTION_GRACE_PERIOD_SECONDS: 300,
  MIN_DISCOUNT_PERCENT: 1,
  MAX_DISCOUNT_PERCENT: 30,
  ORGANIZER_FEE_BPS: 100, // 1.00%
  TREASURY_FEE_BPS: 50,   // 0.50%
} as const;
